eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8762

spring:
  application:
    name: service-goods
  activemq:
     broker-url: tcp://127.0.0.1:61616




Configuration:
  status: warn

  Appenders:
    Console:  #输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      ThresholdFilter:
        level: trace
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: "%d{yy-MM-dd HH:mm:ss,SS}:%4p %t (%F:%L) - %m%n"
    Kafka: #输出到Kafka
      name: KAFKA
      topic: kafkaTest
      ThresholdFilter:
        level: error
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: "%d{yy-MM-dd HH:mm:ss,SS}:%4p %t (%F:%L) - %m%n"
      Property:
      - name: bootstrap.servers
        value: 192.168.0.15:9092

  Loggers:
    Root:
      level: info
      AppenderRef:
      - ref: CONSOLE
      - ref: KAFKA
    Logger: # 为com.xjj包配置特殊的Log级别，方便调试
    - name: com.xjj
      additivity: false
      level: trace
      AppenderRef:
      - ref: CONSOLE
      - ref: KAFKA
    - name: org.apache.kafka #听说这样可以避免递归调用
      level: INFO




